services:
  postgres:
    image: postgres:16
    container_name: shop-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - shopsmart_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shopdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  shopsmart_postgres_data:
